### ISSUE TITLE
Update @apollo/client and fix mocked requests and responses on tests

### ISSUE THREAD

**Issue by ggwadera** [garageScript/c0d3-app#1006]
From PR #1005 the CI checks are failing from this new apollo client version. Looking at the logs you can see that some unit tests fails with a message like this:

```
Missing field 'createdAt' while writing result {
  "content": "A very unique test comment!",
  "submissionId": 104,
  "author": {
    "name": "fake user",
    "username": "fakeusername"
  }
}
```

Which means that Apollo client is now type-checking the mocked request and response objects we have on our tests.

**Comment by flacial** [comment]
This issue doesn't occur anymore. But good to reference (tag).
