### ISSUE TITLE
Add Challenge Description to ReviewCard

### ISSUE THREAD

**Issue by InerLeeLofgren** [garageScript/c0d3-app#1154]
Currently, when I am reviewing code, the first thing I do is open another browser tab to get the description of the challenge.
I propose we add a ChallengeQuestionCard component to ReviewCard. 

Current Review Card:
![image](https://user-images.githubusercontent.com/43965984/138212795-39cbaf4a-e6fe-4393-b38f-74dc5aeb0236.png)

Proposed Review Card:
![image](https://user-images.githubusercontent.com/43965984/138212830-93bb45ea-448d-4513-b698-9e0d38e79d98.png)

The proposed changes would be:
 - Add ChallengeQuestionCard component to ReviewCard.
 - Remove the current challenge title, as the ChallengeQuestionCard already displays this.

**Comment by ggwadera** [comment]
I'd suggest to have the description inside a dropdown or a pop-up modal when you click on the challenge title to avoid wasting too much space when there's many submissions to review. Some challenges have some lengthy descriptions which would take a large part of the screen.

**Comment by flacial** [comment]
@InerLeeLofgren You're working on it?
