### ISSUE TITLE
CI/CD pipeline: failing tests are not stopping vercel deployments

### ISSUE THREAD

**Issue by tomrule007** [garageScript/c0d3-app#1157]
### Issue
 The CI/CD pipeline should prevent code that is failing tests from going live. This issue was exposed by a time related test that started failing on our master branch today.

 Pushing up a non related change caused the CI to display the failed test:
https://github.com/garageScript/c0d3-app/runs/3979312177?check_suite_focus=true

 But did not stop vercel from publishing the changes:
https://github.com/garageScript/c0d3-app/commit/94a5bead6147de53fdde29f05cf8a93b46ff1222#commitcomment-58512155

### Potential Solution

1. disable the vercel plugin for master branch merges
2. add another CI workflow that handles the vercel integration for master branch merges as seen here: https://github.com/vercel/vercel/discussions/4589#discussioncomment-23277

**Comment by flacial** [comment]
This has been enabled:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/35906419/154845347-29db2efd-ea63-4413-91d6-ec4943cf28f1.png">

Since it can't be a PR. May you guys please review it? @songz @SahilKalra98 @anthonykhoa @mino323

**Comment by flacial** [comment]
This issue was resolved by enabling `Require branches to be up to date before merging`
