### ISSUE TITLE
For logged in users, AppNav renders the `notLoggedIn` experience before correctly rendering experience for logged in user

### ISSUE THREAD

**Issue by anthonykhoa** [garageScript/c0d3-app#1161]
# Issue
If a user is logged in already and they land on the curriculum page, the navbar on the top of the page will render a navbar for a not logged in user, and then it will render the navbar for a logged in user(and it stays like this). 

Here, there is a `useEffect` that sets the state of `session`:
https://github.com/garageScript/c0d3-app/blob/07cc8be0e6945ae2fddfe53900ae0036736a8aad/components/AppNav.tsx#L113

The session state is used to determine whether to render the `NotLoggedInAuthNav` or  `LoggedInAuthNav` component. When the callback function of useEffect is called, the state properly gets set, and the `LoggedInAuthNav` will get rendered for users.

However, there will be a flicking of displaying the `NotLoggedInAuthNav` component, which shows `Login` and `Signup` buttons before correctly displaying the `LoggedInAuthNav component`. This happens because useEffect's callback function is not called until after rendering finishes.

# Proposed Solutions
1) Set state of `session` with the correct value before the first render

**Comment by flacial** [comment]
Additional proposals:

1. Use skeletons
2. Set the session in `getServerSideProps`

**Comment by songz** [comment]
How does the landing page work? When I go to c0d3.com I get taken straight to the curriculum component. Could we use the same logic?

**Comment by flacial** [comment]
> How does the landing page work? When I go to c0d3.com I get taken straight to the curriculum component. Could we use the same logic?

Oh, that's interesting. I'll check it out!
