### ISSUE TITLE
DB Cleanup

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#1189]
`select id,name,username,"createdAt","discordAccessTokenExpires" from users ou where (select count(*) from users inr where inr.username=ou.username) > 1;`

We have a few users whose accounts were duplicated (33 users). Must have been a bug with a prior version because this issues did not happen in 2021. The last instance that this happened was 2020 july.

This task is to clean up the duplicates by:

1. For each duplicate user, check which ones has submissons.
2. Delete user without a submission (not used).

**Comment by mino323** [comment]
I got a list of the users with select id,name,username,"createdAt","discordAccessTokenExpires" from users ou where (select count(*) from users inr where inr.username=ou.username) > 1;.
Then checked if their ids had submissions in the submissions table.
SELECT * FROM submission where "userId"=(id) or "userId"=(duplicateId)
If there were no submissions I marked both for deletion. 
If one had submissions I marked for saving.
I did not encounter any duplicates with multiple submissions.
I then deleted users marked for deletion. 
DELETE FROM users where id = (x)
