### ISSUE TITLE
js2 - exercise bug

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#1195]
![image](https://user-images.githubusercontent.com/686933/145924172-1d0fa219-41b4-4e35-b1c8-6c65d44c9861.png)

Given problem has a bug:

![image](https://user-images.githubusercontent.com/686933/145924215-28990138-43e1-43bd-94fb-63ef34d79e82.png)

**Comment by isam007** [comment]
And the test case should also be adjusted to include one more test case to catch the recursion break point.

it('should return false on a string = 3 characters, all different', () =>{
                const result = less3Diff('jkl', 'mno')
                expect(result).toEqual(false)
          })

**Comment by songz** [comment]
To change:

1. The sample solution has a bug, the correct solution is here: https://cdn.discordapp.com/attachments/830050402904703017/920117548467519518/unknown.png
2. Add another test case (above)

**Comment by songz** [comment]
@isam007 can you msg me on discord pls? amayz#6224

**Comment by isam007** [comment]
Just did :)
