### ISSUE TITLE
Update docs on how existing code works

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#1199]
| the codebase is INSANELY convoluted 

Document the lifecycle of a request, and create issues that could be done to reduce the complexity and organize the code

**Comment by flacial** [comment]
A bit of elaboration please?

Something like:

1. Client send request with the arguments x and y.
2. x and y are queried from the users table with Prisma.
3. An object that contains the user info is returned (maybe with an example of the returned object too)

**Comment by songz** [comment]
lifecycle of a request: https://github.com/garageScript/c0d3-app/wiki/A-request-journey

I noticed that in the [resolvers file](https://github.com/garageScript/c0d3-app/blob/master/graphql/resolvers.ts#L23) some resolvers come from `/helpers/controllers/` and some resolvers come from `/queryResolvers/lessons`. We should be consistent.

I noticed alot of resolvers have the same repeating `req.user?` check [like this one](https://github.com/garageScript/c0d3-app/blob/master/graphql/queryResolvers/session.ts#L11), which could be replaced by `withUserInfo` container.
