### ISSUE TITLE
Shared state between tests producing flakey race conditions.

### ISSUE THREAD

**Issue by tomrule007** [garageScript/c0d3-app#1205]
There is a race condition that will cause some of the test suites to conflict with one another when running concurrently. This means some tests are sharing state which is never a good idea.

I believe one of the sources is the handling of apollo cache and this helper file, [helpers/updateCache.ts](https://github.com/garageScript/c0d3-app/blob/master/helpers/updateCache.ts), that interacts with the apollo cache and is [used in all these files](https://github.com/garageScript/c0d3-app/search?q=updateCache)

but there may be more in the meantime you can disable concurrent mode with  `npm run test -- --runInBand`

**Comment by flacial** [comment]
When I disable `--runInBand`, the only component and test failing is `AdminLessonsInfo component › Should update lesson sucessfully` and the error is `thrown: "Exceeded timeout of 5000 ms for a test.`

**Comment by flacial** [comment]
Closing until it happens to be an issue again.
