### ISSUE TITLE
js2 - challenge 3.js missing test for col = 0

### ISSUE THREAD

**Issue by isam007** [garageScript/c0d3-app#1207]
currently this solution to challenge 3 passes all tests and got accepted. 
![image](https://user-images.githubusercontent.com/60295734/146825493-865d5c88-2f67-4a49-b8b0-e451bb02d7f0.png)
However this type of solution shouldn't work if the row > 0, but col = 0! Yet there is no test case to catch that.
![image](https://user-images.githubusercontent.com/60295734/146826272-f45b523a-526f-40c4-affb-146c7bb96b1d.png)

This challenge needs one more test case where row > 0 and col = 0, for example (solution (3, 0)).

**Comment by songz** [comment]
this issue is fixed in this PR into the curriculum repository: https://github.com/garageScript/curriculum/pull/377
