### ISSUE TITLE
Packages to update when NextJS is upgraded to v12

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1288]
1. https://github.com/garageScript/c0d3-app/pull/1269
2. https://github.com/garageScript/c0d3-app/pull/1299

**Comment by songz** [comment]
Also [this](https://github.com/garageScript/c0d3-app/pull/1244)

Which includes:

https://github.com/garageScript/c0d3-app/pull/1208
https://github.com/garageScript/c0d3-app/pull/1236
https://github.com/garageScript/c0d3-app/pull/1246
