### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#1301]
As an engineer, when I start the dev server I get alot of warnings. This is concerning, I should not be seeing any warnings.

We should fix warnings early before it becomes a problem!

<img width="718" alt="Screen Shot 2022-01-14 at 12 40 23 PM" src="https://user-images.githubusercontent.com/686933/149582277-34407fe4-cb17-4ba9-a445-fc6eda852647.png">

**Comment by flacial** [comment]
It's related to #1283
