### ISSUE TITLE
[Markdown Validation] - Warning appears on invalid Mardown

### ISSUE THREAD

**Issue by coltonehrman** [garageScript/c0d3-app#144]
<img src="https://i.imgur.com/BlRtq1B.png" />

**Comment by michaelbayday** [comment]
Not sure this is preventable due to how we formatted our Markdown within our DB

**Comment by michaelbayday** [comment]
Also, I think this only happens with our test DB. PRD database doesnt seem to cause this issue.

**Comment by coltonehrman** [comment]
It appears to only be happening in test environment and not in production
