### ISSUE TITLE
[Refactor] - Use withQueryLoader for GraphQL Queries

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#146]
Refactor parts of the code where components are manually doing:
```
const {....} = useQuery(....)
if (....) {
  return loading...
}
if (error) {
  return error....
}
return component
```

Sample refactor [posted here](https://github.com/garageScript/c0d3-app/pull/145/files)

**Comment by michaelbayday** [comment]
this might be done for now!

**Comment by coltonehrman** [comment]
Moving to #291
