### ISSUE TITLE
Being able to access the login page even if I'm already logged in

### ISSUE THREAD

**Issue by anthonykhoa** [garageScript/c0d3-app#1526]
I can access the login page and login again, even though I'm already logged in. If I'm already logged in, I shouldn't be able to see the login page again, unless we implement some kind of security feature that forces users to login again given some set of circumstances. There should be an internal redirection to some other page if a user is logged in, and tries to access the login page

**Comment by flacial** [comment]
Should be fixed after integrating next-auth. We could've something like this in the login page:

```js
getServerSideProps(({ req, res }) => {
  const session = await getSession({ req })

  if (!session) return res.end()

  return return {
      redirect: {
        permanent: false,
        destination: "/curriculum"
      }
    }
})
```

**Comment by flacial** [comment]
Closed in https://github.com/garageScript/c0d3-app/pull/1953
