### ISSUE TITLE
CLI Version - on user table

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#1552]
As an engineer doing cli upgrades, sometimes I want to know how many users are on a certain CLI version and want make sure that users on older versions are notified. 

To do this, I'm thinking

1. A `cliVersion` column in `user` table.
2. Once [this issue](https://github.com/garageScript/c0d3-app/issues/1551) is implemented, in the `cliToken` user lookup, we could update the `cliVersion`.
3. `c0d3 cli` should send `Authorization Bearer` token that is base64 encoded with: `cliToken` and `cliVersion`

This gives us an ability to lookup all the users with certain version and possibly notify them via discord or email in the future.

**Comment by flacial** [comment]
Issue has be resolved in https://github.com/garageScript/c0d3-app/pull/1625 and https://github.com/garageScript/c0d3-cli/pull/43
