### ISSUE TITLE
Refactoring Resolvers

### ISSUE THREAD

**Issue by SahilKalra98** [garageScript/c0d3-app#1564]
Discussion is posted [here](https://github.com/garageScript/c0d3-app/discussions/1543) and the issues that are covered are #1441, #1200, and #1199

I tried refactoring the files in one PR but the amount of files it would have touched would have been a lot. So I am going to be breaking down these issues into smaller parts in the following order:

- [x] 1. I am going to rename `queryResolvers` to `resolvers` first and change the files that had previously imported from `queryResolvers`

- [x] 2. The next step will be to move the files from `helpers/controllers` into the newly created `resolvers` directory. This step might be broken up to smaller PRs because some of the resolvers have imports from different files so it can become a bit confusing.

- [x] 3. Once the all the resolvers are in the `resolvers` directory then I will refactor the queries/mutations that will make use of fragments which will result in less code duplication

**Comment by flacial** [comment]
Is this still WIP?
