### ISSUE TITLE
Refactor formValidation file

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1652]
https://github.com/garageScript/c0d3-app/pull/1651#discussion_r835832334

> I notice lots of repeated strings in this file. There should be more constants made to be used in this file, rather than repeating the same strings over and over again

[The file location](https://github.com/garageScript/c0d3-app/blob/master/helpers/formValidation.tsx)

**Comment by evo777** [comment]
Yeah, we should vary the examples.
