### ISSUE TITLE
Update error page components to make them reusable 

### ISSUE THREAD

**Issue by rsrelewa** [garageScript/c0d3-app#1657]
We want to make a reusable component for our error pages (e.g. https://www.c0d3.com/admin/lessons)

<details>
<summary>Right now the current page displays the following</summary>
<br>
<img src="https://user-images.githubusercontent.com/81452711/160294894-d6fb6bef-7573-48b7-aae3-dcdd6221d7fd.png">
</details>

<details>
<summary>Right now the current page displays the following</summary>
<br>
<img src="https://user-images.githubusercontent.com/81452711/160295057-ed4c2e09-5bb1-45de-9f87-2154003098a6.png">
</details>

We can update [Error component](https://github.com/garageScript/c0d3-app/blob/master/components/Error.tsx) to be reusable and beautify it so it can be used where applicable.

**Comment by evo777** [comment]
That is a good suggestion.
