### ISSUE TITLE
All Tests should be named FILENAME.test.js instead of FILENAME.js

### ISSUE THREAD

**Issue by hwong0305** [garageScript/c0d3-app#168]
All our application file are written in Typescript with (.ts | .tsx) extension.
All our test files are written in Javascript with (.js) extension.

This could create confusion when looking at filenames if the TypeScript file and JavaScript file has exactly the same name. To work around this issue all test files should be named `flename.test.js`

**Comment by danielthalhuber** [comment]
It looks like this issue can be closed (was resolved by PR #217). The remaining files with `.js` extensions in `__tests__` directories have the correct naming convention (`filename.test.js`). @hwong0305, are you aware of any other test files that should be addressed?

**Comment by hwong0305** [comment]
No. I think this can be closed.
