### ISSUE TITLE
Update LessonNav styles

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1682]
In the last design meeting (1/4/2022) we [updated](https://www.figma.com/file/f9xRyl1bJOjtBRd8zFORzg/c0d3?node-id=574%3A5386) the LessonNav component styles. Update ours with these styles.

**Comment by flacial** [comment]
It will be updated after the next design to make sure whether all of the navigations should look like the newly designed one or not.

**Comment by evo777** [comment]
This is nice!
