### ISSUE TITLE
Redesign sublesson page

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1705]
Redesign [sublesson page](https://github.com/garageScript/c0d3-app/blob/master/pages/curriculum/[lessonSlug]/[subLessonSlug].tsx) with this [mock](https://scene.zeplin.io/project/5e19606fd539a701e62f9d70/screen/5e44ed5893b7ba96ab3bd8c4)

**Comment by evo777** [comment]
Good strategy.
