### ISSUE TITLE
bug: discord component story isn't working

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1758]
![image](https://user-images.githubusercontent.com/35906419/164321570-9f5d9a5f-d801-4548-ae1e-a847d7c2a452.png)

The error originated from attempt to access `jest.fn()` to mock `global.fetch` or `fetch` function. 

- `jest-mock` package isn't installed, and even if it got installed webpack will fail to compile it.

### Solution

- Install [fetch-mock](https://www.npmjs.com/package/fetch-mock)
- Follow its docs to mock each story fetch request.

Example stories fetch mock:

```tsx
export const ErrorFetching: React.FC = () => {
  fetchMock.restore().mock('*', 404)
  return (
    <Wrapper>
      <DiscordBar />
    </Wrapper>
  )
}
```

```tsx
export const EmptyMembers: React.FC = () => {
  fetchMock.restore().mock('*', { presence_count: 0, status: 200, members: [] })
  return (
    <Wrapper>
      <DiscordBar />
    </Wrapper>
  )
}
```

**Comment by shockz09** [comment]
fixed in https://github.com/garageScript/c0d3-app/pull/1817

**Comment by flacial** [comment]
@shockz09 I replaced the solution as the previous one wasn't working. I also added more details and some examples.

**Comment by shockz09** [comment]
i see
