### ISSUE TITLE
Bug: Curriculum and [lessonSlug] test fails randomly

### ISSUE THREAD

**Issue by SlyBouhafs** [garageScript/c0d3-app#1773]
The curriculum test fails randomly when running tests, most of time it passes but there are times where it fails.
The snapshot file keeps getting updated without any changes to the curriculum page.
![Screen Shot 2022-04-24 at 17 23 22](https://user-images.githubusercontent.com/1410462/164986290-20e9e84b-0606-4b8f-888f-bb607bf962d2.png)

**Comment by flacial** [comment]
It's difficult to replicate it.

**Comment by evo777** [comment]
Nice catch.

**Comment by flacial** [comment]
Happened again https://github.com/garageScript/c0d3-app/runs/7331986608?check_suite_focus=true

**Comment by flacial** [comment]
After merging https://github.com/garageScript/c0d3-app/pull/2131 the issue didn't occur again.
