### ISSUE TITLE
fix: Breadcrumbs has extra padding-left

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1805]
Add the property `padding: 0` to [`.breadcrumbs`](https://github.com/flacial/c0d3-app/blob/ba78dd725d754e1442bee06521d0fb3169d09c9f/scss/breadcrumbs.module.scss#L8)

![image](https://user-images.githubusercontent.com/35906419/165819248-8d182f72-16ce-4f9b-b56b-5b0f06c98f4d.png)

**Comment by shockz09** [comment]
fixed
