### ISSUE TITLE
DOJO(admin/page): Create lessons home page

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1959]
Create the following [page](https://www.figma.com/file/f9xRyl1bJOjtBRd8zFORzg/c0d3?node-id=204%3A4488).

To resolve this issue, you must create the following component(s):

- [Lesson card](https://www.figma.com/file/f9xRyl1bJOjtBRd8zFORzg/c0d3?node-id=204%3A4491)

After creating the components, in the next PR, create the page. ADD NEW LESSON and EDIT THE LESSON buttons won't work until the next [pages](https://www.figma.com/file/f9xRyl1bJOjtBRd8zFORzg/c0d3?node-id=906%3A4589) are implemented.

**Comment by evo777** [comment]
Nice.

**Comment by flacial** [comment]
Duplicate of https://github.com/garageScript/c0d3-app/issues/1656

**Comment by HS-90** [comment]
new lessons page merged under path '/admin/lessons/new', but im leaving the issue open for now since we should update/finalize the links in the page once other related admin pages like exercises page, pending questions, etc. are finished.

**Comment by flacial** [comment]
Closed in https://github.com/garageScript/c0d3-app/pull/2538
