### ISSUE TITLE
DOJO(mentor): Create exercises page

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1975]
**Create the following [page](https://www.figma.com/file/f9xRyl1bJOjtBRd8zFORzg/c0d3?node-id=1046%3A5849)**

Required components to be created:

- [x] [Preview card](https://github.com/garageScript/c0d3-app/issues/1819)

Components to be created within the page:

- [x] Inputs form
- [x] Dropdown to switch the lesson module

Misc:

- The page will be accessed through `/mentor/[lessonSlug]/[moduleSlug]/exercise` (could be discussed with engs)

**Comment by evo777** [comment]
Good feature.
