### ISSUE TITLE
Upgrade Prisma to version 3

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1977]
Updating Prisma to v3 will resolve the following issues our engineers had encountered:

- https://github.com/prisma/prisma/issues/11356
- Database doesn't get populated (we assume it's related to Prisma)

[How to upgrade to version 3](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3)

**Comment by evo777** [comment]
Prisma is good.

**Comment by JasirZaeem** [comment]
https://github.com/garageScript/c0d3-app/pull/2026 Version 4 is out as well
https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4
