### ISSUE TITLE
Lesson resolver should query modules & exercises

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2008]
To show a list of the flagged exercises, the lesson query must resolve with its modules and their exercises.

Related to #1990 

To achieve it:

1. Add `modules: [Module!]` to [Lesson type](https://github.com/flacial/c0d3-app/blob/ee23de29522acb5095707b781eb98f843009bb4f/graphql/typeDefs.ts#L205)
2. Add `exercises: [Exercise!]` to [Module type](https://github.com/flacial/c0d3-app/blob/ee23de29522acb5095707b781eb98f843009bb4f/graphql/typeDefs.ts#L245)
3. Update `getApp.ts` to include the `modules`
```graphql
modules {
  id
  name
  exercises {
    id
    description
    answer
    flaggedAt
    flagReason
  }
}
```
4. Update `lesson.ts` to include the modules and their exercises
  ```js
include: {
  challenges: { orderBy: { order: 'asc' } },
  modules: {
    orderBy: {
      order: 'asc'
    },
    include: {
      exercises: {
        include: {
          module: true
        }
      }
    }
  }
}
```

**Comment by evo777** [comment]
Good job, Faisal.
