### ISSUE TITLE
Create withUserContainer helper method

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2017]
Protip for doing this:

1. Create a helper function, we usually call them `containers`

```js
export const withUserContainer = (cb) => {
  return async (
     _parent: void,
     arg: ...,
     { req }: Context
   ): Promise... => {
         const { id } = arg
         const userId = req.user?.id
         if (!authorId) throw new Error('No User')
         return cb(_parent, arg, {req, userId} )
}
```

Then now you can use this container for every resolver you would wish to make sure userId exists:

```js

export const flagExercise = withUserContainer(async () => {} )

export const removeExerciseFlag = withUserContainer( async () => {} )
```

_Originally posted by @songz in https://github.com/garageScript/c0d3-app/pull/2012#discussion_r906688879_

**Comment by evo777** [comment]
Nice.

**Comment by HS-90** [comment]
Reopened for now, will close again once `withAdminContainer` is merged
