### ISSUE TITLE
Remove username from `AppNav`

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2096]
The username next to the user's avatar doesn't add any noticeable value, as the user already knows their name. If the username is used as a cue to "This is your profile menu", the avatar is sufficient. I propose to remove the username.

![image](https://user-images.githubusercontent.com/35906419/179347172-639cd8e7-ad43-4858-94cc-fd51fd589286.png)

**Comment by evo777** [comment]
I agree.
