### ISSUE TITLE
Update our code to reflect the new Bootstrap v5.2.0 changes

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2118]
PR: https://github.com/garageScript/c0d3-app/pull/2117

Useful resources:
- https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/
- https://www.devtopics.com/whats-new-and-interesting-in-bootstrap-5-2-0/

**Comment by evo777** [comment]
The new Bootstrap is good.
