### ISSUE TITLE
Broken urgent alert message background

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2145]
# Problem

![image](https://user-images.githubusercontent.com/35906419/182868614-79502603-b310-4878-b166-c5dfe6e21b6e.png)

It should have a background color.

# Solution

Investigate why the background color went missing. I assume it's related to [upgrading bootstrap](https://github.com/garageScript/c0d3-app/pull/2130)

**Comment by evo777** [comment]
It is weird how that color was missing.
