### ISSUE TITLE
Typo on JS3 Exercise Q2 P2

### ISSUE THREAD

**Issue by pauly48** [garageScript/c0d3-app#2155]
![Capture](https://user-images.githubusercontent.com/61633849/183234741-96678a11-fc6c-4c39-a1df-88b313e0fa67.PNG)

**Comment by pauly48** [comment]
attempting to fix the typo issue

**Comment by pauly48** [comment]
https://github.com/garageScript/c0d3-app/pull/2156

**Comment by flacial** [comment]
Closed in https://github.com/garageScript/c0d3-app/pull/2156
