### ISSUE TITLE
More detailed How-to-contribute page for the wiki

### ISSUE THREAD

**Issue by pauly48** [garageScript/c0d3-app#2161]
Attached Microsoft Word doc includes instructions with images on how to create new issues to report bugs/feedbacks and clone and fork to make pull requests with changes for contribution

[Issue and PR instruction c0d3.docx](https://github.com/garageScript/c0d3-app/files/9275743/Issue.and.PR.instruction.c0d3.docx)

**Comment by SlyBouhafs** [comment]
The wiki page has been updated!
Thank you for the contribution @pauly48 

https://github.com/garageScript/c0d3-app/wiki/How-to-update-content
