### ISSUE TITLE
DOJO(admin): Create Introduction tab

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2173]
Create this [page](https://www.figma.com/file/f9xRyl1bJOjtBRd8zFORzg/c0d3?node-id=1394%3A7694)

You'll use the [FormCard](https://github.com/garageScript/c0d3-app/blob/master/components/FormCard.tsx) component with a bit of modifications to make it work for the layout structure. When `SAVE CHANGES` is hit, it should call the [updateLesson](https://github.com/garageScript/c0d3-app/blob/5a99b96a5bac6fe0a485d4435f07f2ba522a573f/graphql/resolvers/lessonsController.ts#L23) resolver (its hook could be found within GraphQL index file).

Look into the `docFileUrl` inputs. I don't think they're supposed to be this many.

**Comment by evo777** [comment]
I think introduction tabs are good.
