### ISSUE TITLE
JS2 Page3 syntax error

### ISSUE THREAD

**Issue by pauly48** [garageScript/c0d3-app#2187]
Syntax error (it needs semicolon and also remove parenthesis within an array)

![image](https://user-images.githubusercontent.com/61633849/184556466-daf20ab4-6866-4f7a-aaa4-d0e2d5def0fe.png)

**Comment by evo777** [comment]
Good catch.

**Comment by pauly48** [comment]
Pull Request complete

https://github.com/garageScript/c0d3-app/pull/2205

![image](https://user-images.githubusercontent.com/61633849/185511641-24c9b71b-5188-41fb-a2e8-33ac9e2facf6.png)
