### ISSUE TITLE
[Bug] - Submission Approval backend not completing student lessons

### ISSUE THREAD

**Issue by rkalra247** [garageScript/c0d3-app#222]
When a user's submission for the last challenge has been approved, user's lesson status does not updated to passed.

1. ~~[Data remediation](https://github.com/garageScript/c0d3-app/wiki/Code-Snippets#data-redemiation-bug) - There are users who have technically passed a lesson, but does not have isPassed set to true in lesson status table. Need to find out who they are and fix them.~~
2. New users - last submission approval should pass their lesson.

When student completes a lesson, mattermost notifies the lesson channel more than 1 time. It should only notify the channel one time. 

For example, If a student just finished lesson 2 Array, it should only notify the JS2 channel once that a student has completed lesson 2 successfully. 

<img width="772" alt="mattermost bug" src="https://user-images.githubusercontent.com/27792256/83085179-0de9d200-a040-11ea-97cd-f4208f9170b3.png">

**Comment by songz** [comment]
Needs to be implemented.
