### ISSUE TITLE
Alert get dismissed in the admin/alerts page

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2269]
The alert shouldn't be dismissed:

![Screen Recording 2022-09-08 at 2 07 19 PM](https://user-images.githubusercontent.com/35906419/189096027-d34eec1d-7e55-41f9-904d-16fe0144812d.gif)

**Comment by RoySounak** [comment]
@flacial The alert bar should not be closed forcefully, is it your requirement ?
If yes then i would like to contribute

**Comment by anthonykhoa** [comment]
@RoySounak On the admin alerts page, yes.

**Comment by flacial** [comment]
> @flacial The alert bar should not be closed forcefully, is it your requirement ? If yes then i would like to contribute

@RoySounak Sorry for the late response. As @anthonykhoa said, it's in the `/admin/alerts` page. The `X` icon that's used to close the alert shouldn't appear.
