### ISSUE TITLE
Button component should take any html button attributes as a parameter.

### ISSUE THREAD

**Issue by HS-90** [garageScript/c0d3-app#2292]
Right now our custom Button component does not allow us to pass in certain html button attributes as a parameter. Being able to assign these will facilitate testing in the future. 

For example, being able to pass in a `data-testid' prop will allow for easier selection and simulation of clicking a Button in our test files. As of now we use a querySelector by class, which isn't as precise, nor intuitive.

**Comment by anthonykhoa** [comment]
The button component should be able to take in any html attributes as props, not just data-testid
