### ISSUE TITLE
Username.test.js flaky snapshots

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2368]
[username.test.js](https://github.com/garageScript/c0d3-app/blob/master/__tests__/pages/profile/username.test.js) has a flaky state in which the snapshots sometimes fail because something isn't waiting for the promises to resolve before creating the snapshot.

A solution suggested by @bryanjenningz is to run `await findByText(SOME_TEXT_IN_THE_SNAPSHOT)` to make it wait for some text to show in the DOM before creating/updating the snapshot.

**Comment by evo777** [comment]
Nice catch.
