### ISSUE TITLE
[Bug] Users who has hotmail or yahoo will not receive email confirmation

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#245]
since launch, we've received signup issues from server users. When checking our db we realized that they all either have hotmail or yahoo email addresses. we created our own hotmail and yahoo email inbox and we did not receive email confirmations.

`mailgun` doesn't seem to work well with hotmail and yahoo. Please evaluate other email services to see if we can resolve this issue.

**Comment by coltonehrman** [comment]
Found a StackOverflow on an issue that sounds pretty similar https://stackoverflow.com/questions/52452138/delivery-issue-hotmail-and-yahoo#:~:text=The%20solution%20was%20on%20the,again%20later%20because%20it%20works.

**Comment by songz** [comment]
superseeded by this issue: https://github.com/garageScript/c0d3-app/issues/807
