### ISSUE TITLE
Curriculum Page is using deprecated review and challenge links

### ISSUE THREAD

**Issue by stevenlay** [garageScript/c0d3-app#256]
Currently, the curriculum page is redirecting to outdated links:

1. 'Review Submissions':
teacher route is deprecated -> review route

2. 'View Challenges':
student route is deprecated -> curriculum route

<img width="728" alt="image" src="https://user-images.githubusercontent.com/20160586/83987869-6fd6f100-a8f6-11ea-9099-2813c51869ef.png">

**Comment by danielthalhuber** [comment]
It looks like this issue has been resolved by PRs #267 and #259
