### ISSUE TITLE
[Feature] - Make sure student has proper permissions to review student submissions

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#268]
1. If someone did not pass a lesson, they should not be able to see submissions. - Add a check to getSubmission resolver, approve / reject mutation.

Create a helper function `hasPassedLesson(lessonId)`

**Comment by coltonehrman** [comment]
Would like to implement a standard way of page authorization across the app to help with this issue.

**Comment by greenc123** [comment]
I believe it would help to remove links from the chat. 
Just show the notification not `Click here to review the code.`
Something like: `@user has submitted a solution Create a MemeChat.`
