### ISSUE TITLE
[Feature] - Setup CLI Versioning system

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#269]
User request

![Screen Shot 2020-06-09 at 12 14 07 PM](https://user-images.githubusercontent.com/686933/84189886-d5d48d00-aa4a-11ea-8d8b-c83657298a7f.png)

Users using the latest version of cli should not see the error message.

Possible solution: Add CLI version to user column?

**Comment by coltonehrman** [comment]
I believe this feature will be pretty in-depth to implement, could potentially involve redoing how alerts are currently being done.

**Comment by songz** [comment]
not an issue anymore
