### ISSUE TITLE
[Refactor] Decouple UI Components from Data

### ISSUE THREAD

**Issue by danielthalhuber** [garageScript/c0d3-app#275]
Remove data queries from UI components in Storybook. Consider `AppNav` and `LessonCard`/`ReviewCount`. Each relies on a GraphQL query and uses a different approach to dealing with this situation in Storybook:

- `AppNav` comments out the story that would require a query
- `LessonCard`/`ReviewCount` introduces a prop to avoid using a mock for the client provider

For UI component stories, we should either decouple the components from their queries, or decide on a strategy for mocking/using the Apollo client Provider. I recommend that we adopt the decoupling strategy for the sake of simplicity.

More detail in [this wiki article](https://github.com/garageScript/c0d3-app/wiki/UI-Components-with-GraphQL-Queries)

**Comment by songz** [comment]
not an issue anymore. will create another ticket if this is not the case
