### ISSUE TITLE
[Feature] Show challenge title and link when reviewing Submission

### ISSUE THREAD

**Issue by rkalra247** [garageScript/c0d3-app#280]
As a reviewer, when I review a submission I sometimes forget what `3.js` is asking. It takes me about another 5 clicks or so to open up the challenge in a new tab.

Every submission should have a challenge title that links (in a new tab) to the challenge page.

**Comment by coltonehrman** [comment]
Could we have a description that details this issue to see what is expected?

**Comment by SlyBouhafs** [comment]
> Could we have a description that details this issue to see what is expected?

I think instead of a having a link, we should just add the problem description above the solution, here's an image of what i think is expected: 

![Expected_UI_Review](https://user-images.githubusercontent.com/1410462/87161169-0747af00-c2bc-11ea-9ca9-28b5c5f8dd28.png)
