### ISSUE TITLE
List element uses Roboto font instead of Inter

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2820]
## Problem

In the [design specs](https://github.com/garageScript/c0d3-app/wiki/Design-Specs), we chose Inter to be the font for everything except buttons and certain headings. List elements use Roboto font instead of Inter. _The difference might not be obvious in the screenshots below._

## Expected look

![image](https://user-images.githubusercontent.com/35906419/224404938-870662db-4070-4bca-a1b4-fcb9298c0477.png)

## Actual look

![image](https://user-images.githubusercontent.com/35906419/224404992-99e4aea6-6ed3-4d6d-8dc3-b3cb71b0f27b.png)

**Comment by scotthallock** [comment]
Related observation: the font size for list elements is 16px, while the font size for paragraph elements is 15px.
