### ISSUE TITLE
Improve progressCard

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2823]
## Problem

When I complete the curriculum, the `progressCard` component should congrats me for completing the curriculum and provide me with a link to start contributing to c0d3-app instead of `SETUP DEVELOPMENT ENVIRONMENT`.

## Expected UI

![image](https://user-images.githubusercontent.com/35906419/224407388-58a0672d-27f8-4e50-b95b-253bf85948a6.png)

> the text chosen in the above image is only meant as a demonstration.

## Actual UI 

![image](https://user-images.githubusercontent.com/35906419/224407424-8003f4f8-6377-4185-8576-8ec8075879ea.png)

**Comment by scotthallock** [comment]
Another possible improvement:

Right now the progress meter only increases after completing all challenges in a lesson. My progress meter still indicates 85% even though I have completed all but 1 challenge in JS0 ... JS6.

It might be nice to have the progress meter update with each completed (approved) challenge in the core curriculum (JS0 - JS6), so users can see the progress update more frequently.
