### ISSUE TITLE
Add Reviewer Notification Functionality to Discord Bot

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#2849]
### Overview 

Currently, our Discord bot only sends notifications to students when new comments are posted on their submissions. However, we want to ensure that reviewers are also notified when their comments receive a response. To achieve this, we need to add functionality to the bot that sends a notification to the reviewer when their message is responded to.

To implement this functionality, we'll need to add the ability for the bot to mention the reviewer in the notification message. We'll also need to include a link to the message that was responded to so that the reviewer can easily navigate to it.

This feature will improve the review process and ensure that all parties involved are notified when there is new activity on a submission.

## Proposed implementation

- Add the ability for the bot to mention reviewers in notification messages
- Include a link to the message that was responded to in the notification message
- Test the new functionality thoroughly to ensure it works as expected

## Expected Outcome

Reviewers will receive notifications when their messages receive a response on Discord. This will improve communication and collaboration during the review process.

> generated with ChatGPT

**Comment by scotthallock** [comment]
If nobody is currently working on this, I'd like to give it a shot
