### ISSUE TITLE
Bug in Auth

### ISSUE THREAD

**Issue by JasirZaeem** [garageScript/c0d3-app#2865]
https://www.c0d3.com/review/js6 going to a link that requires auth like this, while being logged out, returns a server error (500) instead of redirecting to the log in page as it used to.

Possibly related to this https://github.com/garageScript/c0d3-app/pull/2818

**Comment by flacial** [comment]
I think it's because the review page gets the session through a graphql query, and since when you're logged out you've no session, it throws an error. The review page should send a request to our nextauth api for the session.

**Comment by flacial** [comment]
After investigating the issue, it seems a rule of react hooks has been broken and the server is throwing an error. A hook can't be used inside another hook...

**Comment by flacial** [comment]
Closed in #2876
