### ISSUE TITLE
[GraphQL HOC] replace withQueryLoader with Types from generator

### ISSUE THREAD

**Issue by coltonehrman** [garageScript/c0d3-app#291]
Depends on #292 
Part of #288 

# Problem
Replace all occurrences of `withQueryLoader` to use `graphql` HOC instead.
*Reference - https://www.apollographql.com/docs/react/development-testing/static-typing/#typing-higher-order-components*

- [x]  Replace `withQueryLoader`
  - https://github.com/garageScript/c0d3-app/blob/077bed585af9e5124de2524da9486d476888e5e8/containers/withQueryLoader.tsx#L15-L28

- [x] Replace inside index.tsx page
  - https://github.com/garageScript/c0d3-app/blob/077bed585af9e5124de2524da9486d476888e5e8/pages/index.tsx#L29-L34

- [x] Replace inside curriculum.tsx page
  - https://github.com/garageScript/c0d3-app/blob/077bed585af9e5124de2524da9486d476888e5e8/pages/curriculum.tsx#L92-L97

- [ ] Replace inside curriculum/[lesson].tsx page
  - https://github.com/garageScript/c0d3-app/blob/077bed585af9e5124de2524da9486d476888e5e8/pages/curriculum/%5Blesson%5D.tsx#L58-L63

- [ ] Replace inside review/[lesson].tsx page
  - https://github.com/garageScript/c0d3-app/blob/077bed585af9e5124de2524da9486d476888e5e8/pages/review/%5Blesson%5D.tsx#L69-L74

- [ ] Replace inside profile/[username].tsx page
  - https://github.com/garageScript/c0d3-app/blob/077bed585af9e5124de2524da9486d476888e5e8/pages/profile/%5Busername%5D.tsx#L89-L94

- [x] Replace inside AppNav.tsx component
  - https://github.com/garageScript/c0d3-app/blob/077bed585af9e5124de2524da9486d476888e5e8/components/AppNav.tsx#L152-L157

**Comment by flacial** [comment]
Closing because there isn't much info
