### ISSUE TITLE
[DB Model Types] Add association data to Sequelize data models

### ISSUE THREAD

**Issue by coltonehrman** [garageScript/c0d3-app#292]
Before #288 and #291 

### Problem
Currently, we do **NOT** have model association fields typed inside of our data models.
This prevents being able to use the static type's when working with models.

### Solution
Understand the current data model associations and what additional fields/data are added via these associations and to which models. Manually add these types into each respective model.
*Link describing the issue and how it can be solved: https://sequelize.org/master/manual/typescript.html*

#### User Model Associations
https://github.com/garageScript/c0d3-app/blob/dbf50e724e852e8e49609a500d8bf85db4fbf578/helpers/dbload.ts#L60-L67
https://github.com/garageScript/c0d3-app/blob/dbf50e724e852e8e49609a500d8bf85db4fbf578/helpers/dbload.ts#L71-L82

#### User Model *(missing association field types)*
https://github.com/garageScript/c0d3-app/blob/dbf50e724e852e8e49609a500d8bf85db4fbf578/helpers/models/User.ts#L3-L19

#### Usage of User Model
https://github.com/garageScript/c0d3-app/blob/dbf50e724e852e8e49609a500d8bf85db4fbf578/graphql/resolvers.ts#L47-L54

*Should be*
```
const [user: UserModel, submissions: SubmissionModel[], lessonStatus: UserLessonModel[]] = await Promise.all([
  User.findOne({ where: { id: userId } }),
  Submission.findAll({
    where: { userId },
    include: [{ model: User, as: 'reviewer' }]
  }),
  UserLesson.findAll({ where: { userId } })
])
```

**Comment by songz** [comment]
we use prisma now :)
