### ISSUE TITLE
"No Data..." error when loading the review page

### ISSUE THREAD

**Issue by SlyBouhafs** [garageScript/c0d3-app#313]
Sometimes i get "No Data..." error when i load the review page, I had to refresh 3 times to get to the actual page  :

![Capture d’écran 2020-07-12 à 1 50 12 AM](https://user-images.githubusercontent.com/1410462/87245640-e491d380-c43e-11ea-83a8-0cdbe05e289f.png)

I do not know any steps to reproduce this bug, it happens randomly every now and then .

**Comment by danielthalhuber** [comment]
Session length may be a factor. More feedback:

<img width="878" alt="no-data" src="https://user-images.githubusercontent.com/32470229/88208937-ced29a00-cc06-11ea-880e-b672d9b267f4.png">

**Comment by danielthalhuber** [comment]
<img width="639" alt="no-data-2" src="https://user-images.githubusercontent.com/32470229/88324365-75d33680-ccd8-11ea-8ac3-6455f8cad773.png">

**Comment by SlyBouhafs** [comment]
Not sure if it is related to this issue but today at around 13:45 GMT i kept getting "Bad Data" after many refreshes on the curriculum page.
![Capture d’écran 2020-08-05 à 1 42 00 PM](https://user-images.githubusercontent.com/1410462/89414494-65807a00-d722-11ea-944d-8ce12f2ac838.png)

**Comment by SlyBouhafs** [comment]
> Not sure if it is related to this issue but today at around 13:45 GMT i kept getting "Bad Data" after many refreshes on the curriculum page.
> ![Capture d’écran 2020-08-05 à 1 42 00 PM](https://user-images.githubusercontent.com/1410462/89414494-65807a00-d722-11ea-944d-8ce12f2ac838.png)

Looks like my session timed out and it wasn't redirecting me to the login page, I solved it by going to the login page manually and login to make it work.

**Comment by songz** [comment]
dosen't seem like its happening anymore. Time heals all bugs eventually :)
