### ISSUE TITLE
[Bad Link] - View Challenges Button

### ISSUE THREAD

**Issue by coltonehrman** [garageScript/c0d3-app#317]
The "View Challenges" button not utilizing internal `<NavLink />` for `next/link` routing.

<img width="769" alt="Screen Shot 2020-07-13 at 10 14 20 PM" src="https://user-images.githubusercontent.com/12456288/87379577-3711e380-c556-11ea-86b1-d75480c1f32f.png">

**Comment by ggwadera** [comment]
I think this has already been done? 

This [commit](https://github.com/garageScript/c0d3-app/commit/8ad40d370c9eb142cfc7edd775e1d5dcbdf3bd49) changed the links to use `<NavLink />`.

@songz could you check this so we can close the issue?
