### ISSUE TITLE
[Bug] As a reviewer, I need to know for which challenge I am reviewing

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#322]
As a reviewer, I would need to know the challenge for the problem to which I am reviewing. Currently I have no way to tell.

![Screen Shot 2020-07-15 at 1 46 32 PM](https://user-images.githubusercontent.com/686933/87594399-be1fa280-c6a1-11ea-807a-d02c40325065.png)

**Comment by rkalra247** [comment]
Need to show the Challenge Question/Prompt

**Comment by danielthalhuber** [comment]
Not sure if we need a new issue for it, but I think this would be valuable. I'm typically keeping two tabs open when I need to consult the challenge description.

**Comment by kondanna** [comment]
![Capture](https://user-images.githubusercontent.com/16906103/110199583-b0ea3a80-7e61-11eb-9c65-1bb9be52af3a.PNG)

Issue has been resolved.
