### ISSUE TITLE
C0d3 CLI keeps asking for credentials

### ISSUE THREAD

**Issue by SlyBouhafs** [garageScript/c0d3-app#367]
Holà,

### Issue

When away from my machine after sometime, when solving problem and submitting, the c0d3 cli asks for my credentials.

### Steps to Reproduce

Here's how it happened:
Switch branch, solve, submit, it asks for credentials, submit works, after 2-4h of non-related stuff, get back to solving, switch branch, solve, try to submit, it asks for credentials again.

It could be an issue with the token, it probably expires after some time.

**Comment by songz** [comment]
not an issue anymore, but if this happen again please file issue with c0d3 cli: https://github.com/garageScript/c0d3-cli
