### ISSUE TITLE
[Bug] - Book Page

### ISSUE THREAD

**Issue by hwong0305** [garageScript/c0d3-app#386]
If you navigate directly to `https://c0d3.com/book` it leads to c0d3.com first. 

The redirection only works if the user is already on c0d3.com.

**Comment by coltonehrman** [comment]
Weird, it seems like it only happens if you use the protocol in the url. If you try `c0d3.com/book` it works

**Comment by coltonehrman** [comment]
Uploaded screenshot of network tab.

Getting 302 status (NOT FOUND) when navigating directly to the url `https://c0d3.com/book`

<img width="1440" alt="Screen Shot 2020-09-08 at 1 22 54 PM" src="https://user-images.githubusercontent.com/12456288/92513762-70717300-f1d6-11ea-8568-5375d5ce09c2.png">

**Comment by ggwadera** [comment]
Closing this as the redirection has been fixed.

See [this message on the chat](https://chat.c0d3.com/c0d3/pl/a1m6hwbyhbf7dg3i4xannksfua) for more details.
