### ISSUE TITLE
Admin Alerts Page

### ISSUE THREAD

**Issue by anthonykhoa** [garageScript/c0d3-app#394]
# The problem

Currently, admins have to either go to a graphql playground or write code that sends a graphql request in order to add or remove an alert. It is inconvenient to do either option.

# Solution

Create an Admin Alerts page so that admins can more easily add or remove alerts on the production site.

# Design

All alerts will be displayed with the [Alert component](https://github.com/garageScript/c0d3-app/blob/master/components/Alert.tsx)

1) Use [AdminLayout](https://github.com/garageScript/c0d3-app/blob/master/components/admin/AdminLayout.tsx) component with loaded data from [withGetApp](https://github.com/garageScript/c0d3-app/blob/master/graphql/index.tsx#L2008) function. `withGetApp` makes a [getApp](https://github.com/garageScript/c0d3-app/blob/master/graphql/queries/getApp.ts) query to the graphql endpoint for c0d3.com. Relevant to this feature, it retrieves data containing
    1) The user's `admin rights` to verify if they can see the admin page(`or an error message is displayed`).
    2) All current `alerts` in the database

2) Display all current alerts in the database as they would be displayed on the production site.
<img width="843" alt="Screen Shot 2020-09-11 at 6 35 53 PM" src="https://user-images.githubusercontent.com/45890848/92984304-1f73b000-f45e-11ea-9198-6efd145629b6.png">

3) Add a `Remove Alert` button to the displayed alerts that will allow users to delete the alert from the production database.
    * On the front end, clicking the `Remove Alert` button will send a `removeAlert` mutation request to the graphql endpoint for c0d3.com. The `removeAlert` mutation request has not been made yet, and will be put in the [graphql/queries](https://github.com/garageScript/c0d3-app/tree/master/graphql/queries) folder 
    * On the back-end, this mutation request will use the [removeAlert graphql resolver](https://github.com/garageScript/c0d3-app/blob/master/helpers/controllers/alertController.ts#L39) in order to delete an `alert` from the production database.
        <img width="471" alt="Screen Shot 2020-09-14 at 7 06 32 PM" src="https://user-images.githubusercontent.com/45890848/93156677-76c38b80-f6bd-11ea-8abb-3e904078fc80.png">

4) Use [FormCard](https://github.com/garageScript/c0d3-app/blob/master/components/FormCard.tsx) component to use as a form. Use the form to add option of adding new alert into database, and display it above the displayed `current alerts in database`.
    * On the front end, clicking the `Add Alert` button will send an [addAlert](https://github.com/garageScript/c0d3-app/blob/master/graphql/queries/addAlert.ts) mutation request to the graphql endpoint for c0d3.com. On the backend, the [addAlert graphql resolver](https://github.com/garageScript/c0d3-app/blob/master/helpers/controllers/alertController.ts#L15) is used to add an alert to the production database.
        <img width="387" alt="Screen Shot 2020-09-11 at 6 43 33 PM" src="https://user-images.githubusercontent.com/45890848/92984405-bb9db700-f45e-11ea-9529-5fc2defd867c.png">

5) Add `preview` feature above `the form to add an alert`. The preview should be updated as the user types into the form.
        <img width="478" alt="Screen Shot 2020-09-11 at 6 44 18 PM" src="https://user-images.githubusercontent.com/45890848/92984420-d1ab7780-f45e-11ea-9dca-f2489729ca4a.png">

6) Use error checking functions in [adminHelpers file](https://github.com/garageScript/c0d3-app/blob/master/helpers/admin/adminHelpers.ts#L49) that use [Yup API](https://github.com/jquense/yup) to error check fields in the `Add New Alert` form
    * A schema for alerts needs to be created in the [form validation](https://github.com/garageScript/c0d3-app/blob/master/helpers/formValidation.tsx) file in order to error check the `Add New Alerts` form with `Yup API`

# Layout of the Admin Alerts Page
![fck](https://user-images.githubusercontent.com/45890848/93156461-13d1f480-f6bd-11ea-848b-4d877f92b402.png)

**Comment by coltonehrman** [comment]
Looks good! 👍

**Comment by songz** [comment]
nice looks awesmoe!
