### ISSUE TITLE
CLI should check the file size when submitting files for review

### ISSUE THREAD

**Issue by SlyBouhafs** [garageScript/c0d3-app#435]
A user submitted the `package-lock.json` file and it made the review page load forever, causing it to crash. So if a user with a bad intention wants to make the review page unresponsive, he'll probably just have to submit a big file to make the review page unusable.

Possible solutions:
1. Disallow the submission of the `package-lock.json` file because many students actually do submit it by error.
2. Check the file size before submitting for review.

**Comment by songz** [comment]
could you file it in this repo please? https://github.com/garageScript/c0d3-cli
