### ISSUE TITLE
[Feature] Better error screens

### ISSUE THREAD

**Issue by Ulisseus** [garageScript/c0d3-app#467]
Right now when you open  [https://www.c0d3.com/curriculum](https://www.c0d3.com/curriculum) without signing up first you get this basic error screen:
![curriculum](https://user-images.githubusercontent.com/3845012/104737911-ea51d400-5755-11eb-9f9d-ea6478cc1dce.png)
Review error screen [https://www.c0d3.com/review/2](https://www.c0d3.com/review/2):
![reviewError](https://user-images.githubusercontent.com/3845012/104738433-8ed41600-5756-11eb-850a-14d509e0ba3a.png)
And 404 error screen is probably the default one from next.js:
![404](https://user-images.githubusercontent.com/3845012/104738888-233e7880-5757-11eb-84bc-673524020191.png)

**Comment by ggwadera** [comment]
Closed by #484 and #485.
