### ISSUE TITLE
Improve website performance and SEO score

### ISSUE THREAD

**Issue by ggwadera** [garageScript/c0d3-app#488]
c0d3.com scored really poorly on https://gtmetrix.com/ -> site that PayPal merchants use to make sure their site scores well on SEO and stuff.

![image](https://user-images.githubusercontent.com/16023489/106812851-ff33d000-664e-11eb-9e6b-92ebfdd775b6.png)

Ideas on how to improve the score?

- change the API query on the index page to only get the session (see the [`getApp`](https://github.com/garageScript/c0d3-app/blob/master/graphql/queries/getApp.ts) query to check everything it requests right now)
- server side redirect to curriculum page ([ref](https://dev.to/justincy/client-side-and-server-side-redirection-in-next-js-3ile))
- Give image elements an explicit height and width. If responsive design is desired, then specifying the `aspect ratio` would also suffice. (Use [`next/image`](https://nextjs.org/docs/api-reference/next/image))
- Resolve accessibility issues

_Issue created from a [Mattermost message](https://chat.c0d3.com/_redirect/pl/ugxqo47igt8h9nj4tfzxpb34io) *by @songz*._

**Comment by hwong0305** [comment]
The following are the suggestion for improvements from Lighthouse

- Give image elements an explicit height and width. If responsive design is desired, then specifying the `aspect ratio` would also suffice.
- Change the navigation bar design so there's more of a contrast between the background and foreground

**Comment by ggwadera** [comment]
> - Give image elements an explicit height and width. If responsive design is desired, then specifying the aspect ratio would also suffice.

Next.js provides a [built-in solution](https://nextjs.org/docs/basic-features/image-optimization) for this by using the [`next/image`](https://nextjs.org/docs/api-reference/next/image) component in our own components.

**Comment by Ulisseus** [comment]
Performance after making landing page static.
![performance](https://user-images.githubusercontent.com/3845012/112968321-da427180-9154-11eb-9869-5560a0e18c17.png)
Compare speed visualization. No loading spinner is much better user experience.

**Comment by flacial** [comment]
Has been fixed. The SEO and Performance score is **A**
