### ISSUE TITLE
[Feature] See star comments on user profile

### ISSUE THREAD

**Issue by ggwadera** [garageScript/c0d3-app#499]
Currently the comments that the users submit when giving a star aren't available through the app UI.

These comments should be publicly displayed on the profile of the user that received the star.

**Comment by kondanna** [comment]
it's not giving me the option to assign to myself, so I'll comment that I'm working on this issue

**Comment by ggwadera** [comment]
> it's not giving me the option to assign to myself, so I'll comment that I'm working on this issue

I invited you to the organization, check your email. You should be able to assign yourself after accepting.

**Comment by kondanna** [comment]
feature merged into master.
