### ISSUE TITLE
Update Additional Resources menu

### ISSUE THREAD

**Issue by Ulisseus** [garageScript/c0d3-app#548]
"Github basics" link doesn't go anywhere. 
"Help & Support" and "Setup Instructions" are duplicates. Should we remove them? 
And even new students probably already know about stackoverflow (it's one of the top search results for anything coding related). 

I propose to changes it to something like this.
* [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Learn)
* [The Modern JavaScript Tutorial](https://javascript.info/). It's not really a tutorial, more like a guidebook but it's rather in-depth. 
* [The missing semester](https://missing.csail.mit.edu/). Various tools, git, vim, grep, tmux and etc.
* [Full Stack open](https://fullstackopen.com/en/)
* [Teach Yourself Computer Science](https://teachyourselfcs.com/)

Feel free to add/remove anything.

**Comment by ggwadera** [comment]
I think this is great. Are you thinking about adding a new page or just changing the sidebar links?

**Comment by Ulisseus** [comment]
I was thinking about expanding sidebar menu a bit. We have plenty of space for sidebar anyways. Something like link+short description.
