### ISSUE TITLE
Feature (from #483) - give students ability to comment on review

### ISSUE THREAD

**Issue by kondanna** [garageScript/c0d3-app#585]
Maybe each submission can have multiple comments, from one or more reviewers and the student. More like a conversation.

**Comment by ggwadera** [comment]
Another suggestion is to be able to comment on individual lines similar to Github PR reviews.

One issue that may arise for this one is that the submissions table only has a single comment field for each entry. To be able to have multiple comments we'll probably need to change some things on the database and have another table for the comments with a many-to-one relation.

Also the mock-ups on Zeplin display a very nice review screen, we could take them as inspiration.

![28  Review Challenges - View Challenge](https://user-images.githubusercontent.com/16023489/112635131-338b6780-8e1a-11eb-8746-93326a0cf260.png)
![29  Review Challenges - View Accepted Challenge](https://user-images.githubusercontent.com/16023489/112635136-34bc9480-8e1a-11eb-94c2-10a96317af8e.png)

**Comment by Ulisseus** [comment]
I tried to implement github-like comments but after a few unsuccessful attempts I switched to other things.
 
If I remember correctly we're using two libraries - one for parsing submission string and another for highlighting differences. 

One approach is to store all lines in a state. When you click on a line it inserts new component discussion component. Cons. You need to implement highlighting by yourself and it's not an easy task at all. Otherwise you need to modify highlighting library so it can include state. Again not easy. 

I agree that we should improve review form. Maybe even integrate it into github somehow.

**Comment by kondanna** [comment]
> Another suggestion is to be able to comment on individual lines similar to Github PR reviews.
> 
> One issue that may arise for this one is that the submissions table only has a single comment field for each entry. To be able to have multiple comments we'll probably need to change some things on the database and have another table for the comments with a many-to-one relation.
> 
> Also the mock-ups on Zeplin display a very nice review screen, we could take them as inspiration.
> 
> ![28 Review Challenges - View Challenge](https://user-images.githubusercontent.com/16023489/112635131-338b6780-8e1a-11eb-8746-93326a0cf260.png)
> ![29 Review Challenges - View Accepted Challenge](https://user-images.githubusercontent.com/16023489/112635136-34bc9480-8e1a-11eb-94c2-10a96317af8e.png)

Perhaps add a Review_Comments table that's a many-to-one for each submission? 
And drop the comment column from submissions table?

Initial thought was to just implement the flat comments structure seen in the Zeplin mockups but I'll look into this GH-style commenting (with syntax highlighting?!)

**Comment by kondanna** [comment]
Could putting the submission diff inside mdx components help with this? 

It may provide syntax highlighting. And possibly the commenting thing.

**Comment by Ulisseus** [comment]
Sorry, I missed this comment. 

I don't really understand how mdx could help with it though. It has a component for syntax highlighting but it's a different type of highlighting. For reviews we need to check for changes, for example, previously line 50 had `const a = 'foobar`, now it has `const a = 'foo'` and while comparing one string to another is pretty easy it becomes a rather non-trivial task when you change the order or just add empty lines.

**Comment by ggwadera** [comment]
> Could putting the submission diff inside mdx components help with this?
> 
> It may provide syntax highlighting. And possibly the github-like commenting feature.

The diff syntax highlighting works a little differently on that case. Instead of highlighting the entire code block in a single pass it highlights the code line by line, through a custom rendering function passed to the diff viewer component.

**Comment by Ulisseus** [comment]
Line-comments are live but sometimes you don't want to add comment to specific line, you just want to post a message under submission.

Adding submission comments will be easier, but I still need to break it into multiply PRs:
* backend changes
* refactoring updateCache into separate function, refactoring `mdInput`
* changes to `ChallengeMaterial` and `ReviewCard`

**Comment by kondanna** [comment]
line comments feature implemented by PR #585
