### ISSUE TITLE
Migration to AWS SES from MailGun

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#807]
Our AWS SES has been approved, this migration would close this issue: https://github.com/garageScript/c0d3-app/issues/245

# problem

since launch, we've received signup issues from server users. When checking our db we realized that they all either have hotmail or yahoo email addresses. we created our own hotmail and yahoo email inbox and we did not receive email confirmations.

mailgun doesn't seem to work well with hotmail and yahoo. 

Also, users are complaining about emails not arriving (cause: email takes too long to be delivered)

# Conclusion

Seems like MailGun is unreliable. Others are having the same issue: https://stackoverflow.com/questions/52452138/delivery-issue-hotmail-and-yahoo#:~:text=The%20solution%20was%20on%20the,again%20later%20because%20it%20works

# Solution

Migrate to AWS. 

Sample Code:

```javascript
const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  host: "email-smtp.us-east-2.amazonaws.com",
  port: 465,
  secure: true, // upgrade later with STARTTLS
  auth: {
    user: process.env.SMTP_USERNAME,
    pass: process.env.SMTP_PASSWORD,
  },
});

transporter.verify(
  (err, success) => console.log("err", err) && console.log("success", success)
);

transporter
  .sendMail({
    to: "example@outlook.com",
    from: "admin@c0d3.com",
    subject: "you have a gif msg",
    html:
      "<h1>YOU RE AWESOOOOOME</h1>",
  })
  .then(console.log);
```

**Comment by ggwadera** [comment]
Node mailer has support for a SES transport https://nodemailer.com/transports/ses/
