### ISSUE TITLE
Page not found on lessons routes

### ISSUE THREAD

**Issue by Ulisseus** [garageScript/c0d3-app#826]
Going to any `c0d3.com/curriculum/*` page results in 404 lesson not found error screen quickly transitioning to the correct page.

**Comment by ggwadera** [comment]
Can you reliably reproduce this issue on the prod deployment? I'm not able to.

**Comment by Ulisseus** [comment]
It's sneaky, that's how it [looks](https://discord.com/channels/828783458469675019/836343487531712512/841025806615969833). I have troubles to reliable reproduce it too, but I definitely noticed it a few times in production.
