### ISSUE TITLE
Incorrect rendering of long submissions

### ISSUE THREAD

**Issue by Ulisseus** [garageScript/c0d3-app#832]
![reviewBug](https://user-images.githubusercontent.com/3845012/120272601-0f368600-c2b6-11eb-8a33-eafa7f70a4a0.png)

It's not consistent, I can't reproduce it reliable. Refreshing the page fixes it.

**Comment by songz** [comment]
I see it too!

**Comment by flacial** [comment]
Doesn't occur anymore. If it does, I'll reopen this issue and investigate it.
