### ISSUE TITLE
Stars Component

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#842]
# Design Docs
Design documentation. Need to figure out why you need one? [Read about Design Docs at Google](https://www.industrialempathy.com/posts/design-docs-at-google/)

# Stars Component
This component is supposed to give students an opportunity to give a star to a mentor who helped them throughout the lesson. When a student completes a lesson, they will get a chance to thank someone who have mentored them. 

The goal of this feature is to promote a culture of helpfulness, where students who take the time out to review others gets a chance to be recognized for their efforts.

## User Experience
There are user experiences from 2 perspectives, the student and the mentor. 

### Student
Lesson Completion - Upon user completion, a Modal should show up. User selects a person to receive the star and writes a reason why. 

![Screen Shot 2020-07-30 at 10 36 52 AM](https://user-images.githubusercontent.com/686933/88955380-b0951b80-d250-11ea-8c0e-1561d2097b51.png)

* Todo
  * User Search GraphQL - takes in 2+ characters, returns a list of users that matches the username / name
  * Get Users Who completed a lesson - given a lesson id, return a list of usernames, name, and id of users who have completed the lesson.
    * Don't query all the users in the database.
    * i.e. ```getLessonMentors()``` -> Should take in only lessonId as an argument
  * UI Components
    * Modal, User Card (reuse profile card or create own), User Search component.
      * Filter out self.
      * When user starts typing in the input box, it should filter through the mentor list and find the correct one. [Example](https://app.zeplin.io/project/5e19606fd539a701e62f9d70/screen/5e44ed551858a5b453e44448)
    * User can click on submit and a thank you message should pop up acknowledging the star has been given. [Example](https://app.zeplin.io/project/5e19606fd539a701e62f9d70/screen/5e44ed5557b4ff8a25025e1f)
    * There should be an ```onmouseover```/```hover``` effect when user is selecting his/her mentor [like this.](https://app.zeplin.io/project/5e19606fd539a701e62f9d70/screen/5e44ed551858a5b453e44448)
* Give Star GraphQL Mutation - give star to user for a particular lesson.
  * Mutation -> ```giveStar()``` -> Should take lessonId, comment, userId, and mentorID as arguments
  * Assign star between the student and mentor and save it into the database
  * Update Mattermost lesson channel by emitting a message such as ```@noob received a star!```
    

After sending a Star, users should see the comment they've written and an option to change it (no UI mockups, best effort)

![Screen Shot 2020-07-30 at 10 42 24 AM](https://user-images.githubusercontent.com/686933/88955933-7c6e2a80-d251-11ea-94a4-e68ccb156bbe.png)

Currently on when you complete a lesson, there is a Challenges Completed Card that shows up with a button option of giving a star to a mentor.
When User clicks on the ```Give Star``` button, the modal (above section should show up). Otherwise, the `Give Star` button should show a star indicating who the star was given to.

* Todo
  * student - app query would need to include stars given to others (to be displayed on lesson page)

### Mentor
When someone receives a star, the chatroom will be updated that someone has received a star.

Mentor's profile page should show a list of all the stars received. 

**Ignore the bravo section**
![Screen Shot 2020-07-30 at 10 40 29 AM](https://user-images.githubusercontent.com/686933/88955729-2b5e3680-d251-11ea-8b21-fe4b51376d64.png)

* Todo
  * Update GraphQL for APP query to send back stars for each lesson.
  * (UI) Display number of stars to next to each lessonid, and total stars.
  * User profile query would need to include stars received for the user

### Database
1. Currently in ```helpers/models/Star.ts``` - The Star types don't match up with the model that is implemented
2. After fixing the types, add the correct relationships in ```dbload.ts```
   * i.e. ```Star.belongsTo(User, { as: 'student' })``` and ```Star.belongsTo(User, { as: 'mentor' })```

---

# Admin
Admin page for setting user permissions, managing the platform

## Overall tasks that needs to be done for admin page:

1. Add middleware for all graphql requests coming in to populate `req.user`.
2. Refactor all code [like this](https://github.com/garageScript/c0d3-app/blob/4367952888c6e7a99c19f1e9a9d4f8de596149fc/graphql/resolvers.ts#L42) to simply check `if (!req.user) `....

## Admin Resolvers

Applies to all resolvers - Reject request if `!req.user.isAdmin`

1. Query for all users in the db
2. `setAdmin` Mutuation to make a user an admin 
3. Mutation to create new lesson
   * update existing lesson
4. Mutation to create new Challenge for a lesson
   * update existing challenge
5. Update (existing) alerts Mutation - check for admin status.

## Admin UI Pages
1. `/admin/users` - View all users and make them admin / not. 
   * Nice to have: filter by admin vs non-admin / input search for username filtering
2. `/admin/lessons` - View all lessons, ability to select lesson and update its corresponding challenges.
3. `/admin/alerts` - View all alerts, ability to create / delete alerts.

## Undecided
1. delete lesson -> corresponding challenges must be deleted as well?
   * corresponding `UserLesson` as well?
2. delete challenge -> corresponding submissions must be deleted as well?

**Comment by ggwadera** [comment]
> 1. delete lesson -> corresponding challenges must be deleted as well?
>     - corresponding UserLesson as well?
> 2. delete challenge -> corresponding submissions must be deleted as well?

Currently the database is setup to cascade delete these when removing the top-level relation. So removing a lesson deletes all the challenges, and deleting a challenge deletes all the submissions related to it.

**Comment by songz** [comment]
Closing this, because feature is complete and stable.
