### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#843]
# Problem
Ever since [migration to Discord from Mattermost](https://github.com/garageScript/c0d3-app/wiki/Process-Changes), when students make submissions, our Discord server doesn’t get notifications.

# Goal
Our goal is to bring back the feature to keep mentors / students more engaged and be aware of student activity. This way, students could get faster code review feedback. 

1. When users submits a challenge for a lesson X, we should update our discord channel for lesson X + 1 to students who have completed the lesson know that there has been a new submission. 
2. When a submission has been approved, we check to see if the user has completed all the challenges for the given lesson. If so, we progress them to the next lesson and send a congratulatory message to the lesson X channel. And then welcome the user into the lesson X+1 channel.
3. We may also want to display a user's discord information on their c0d3 profile page. 

In the future, we may just use Discord login instead of c0d3.com login. Also, possibly notify student when a comment is made on a submission.

To accomplish these features, we need to solve the following high level problems:

1. How to correlate users’ Discord account to their c0d3.com account? (OAUTH after login)
2. How to notify the lesson’s corresponding channel when users make a submission?

# Architecture

# Research
Since all of the unknowns are within the Discord API, our research focuses mainly around answering questions about the Discord API.

**Correlating User’s Discord Account to c0d3.com account**
* Best way to do this is using [discord OAUTH2 API](https://discord.com/developers/docs/topics/oauth2). This gives us the refresh token, auth token, which we can then use to fetch user’s discord info.
* [test demo](https://demo.songz.dev/discord) and [result](https://demo.songz.dev/discord/profile)
* [next-auth](https://next-auth.js.org/adapters/models) has an adapter for prisma and built in sign in functions and session handling, but we would need to add 2 or 3 more models to our schema and they provide no way of retrieving another user's discord info in real time, which is what we want

**How to notify the lesson’s corresponding channel when users make a submission**
* Create a bot and invite it to our guild/server. [Sample link](https://discord.com/oauth2/authorize?client_id=845470281283665970&scope=bot+applications.commands)
* [Official bot nodejs module](https://github.com/discordjs/discord.js#readme)

**How to get channel ID**
* Go to User Settings > Advanced > Activate Developer Mode
* Now when you right click on channel, there's an option to copy channel ID

**Terminologies**
* Our Guild ID for c0d3: [828783458469675019](https://github.com/garageScript/c0d3-app/blob/da7646955746a357eea908a9b8a16a62f42ef305/components/DiscordBar.tsx#L30)
  * Within our Guild, we have multiple **channels** like (JS0-JS6).
 
**Questions**
* After users authorizes our app, we get `auth_token` (this expires). Does `refresh_token` ever expire? [No, the refresh token only expires when the user unauthorizes the application through their settings](https://gist.github.com/Vap0r1ze/776b0f841ce01fc2b0801933b79960df)
  * `auth_token` comes with `expires_in` with is in seconds. When we tested this, the value was `604800`, which is 7 days
* What scopes may we want to ask the user for?
  * `email` - In the future, we may want to use discord email in place of email verification during signup. 
    * Further research needed: How do we know if the user has verified their email with discord? Are users able to oauth apps when their emails has not yet been verified?)
  * `gdm.join` - allows our app to join users [to a group dm](https://discord.com/developers/docs/resources/channel#group-dm-add-recipient). This could add an interesting feature for the future where we add users to relevant channels only after lesson completion.
    * Further research: Could we put 2 users in a group chat together? If we could, perhaps we could create a message between reviewer and student after submission review to facilitate communication between them?
  * `guilds.join` - When users are not currently in c0d3 guild, after OAUTH we should automatically join them into our guild.
  * `identify` - For getting username and profile picture
* what bot permissions do we need and why

**Comment by kondanna** [comment]
# Architecture Changes
![userinfo](https://user-images.githubusercontent.com/16906103/121000810-4fed3e00-c793-11eb-8236-d374d75a15ce.png)
![codecli](https://user-images.githubusercontent.com/16906103/121000822-54195b80-c793-11eb-9398-35f288d06d84.PNG)

**Comment by kondanna** [comment]
Subtasks
* add new Connect to Discord page at route /discord
![Capture](https://user-images.githubusercontent.com/16906103/121000945-727f5700-c793-11eb-95eb-9f52bc5cfbe1.PNG)
* add new column refresh_token to User table
* add new column discord_channel_url to Lesson table
* in getSession resolver, check if refresh_token exists and is valid
    * if no, direct user to /discord
    * if yes, store the new token after token exchange and direct user to /curriculum 
* in createSubmission and userInfo resolvers, use refresh_token to get access_token, then use access_token to get username and avatar
    * when user submits challenge submission with c0d3-cli), notify channel
    * when user navigates to /pages/profile/username, they will see that user’s most recent username and avatar, and update their refresh_token in DB
* create new UI component to show Discord user info in profile page

**Comment by kondanna** [comment]
In Sprint Grapefruit, we considered using Next Auth to do the Discord OAuth2 Integration.

I'm running into a similar issue to this guy:
https://github.com/nextauthjs/next-auth/issues/296

The error url is: http://localhost:3000/api/auth/signin?error=OAuthAccountNotLinked

Attached screenshot:
<img width="335" alt="Capture" src="https://user-images.githubusercontent.com/16906103/124280948-ea059380-db51-11eb-96c9-aa08b63102e0.PNG">

**Comment by songz** [comment]
closing because feature is complete!
