### ISSUE TITLE
Add a way for a reviewer to see previous submissions [feature]

### ISSUE THREAD

**Issue by Ulisseus** [garageScript/c0d3-app#874]
**Why is this needed?**
Being able to compare previous attempts would allow reviewer to provide better feedback. Currently, only the most recent submission is visible and all comments are reset on re-submission. 

Every diff should get a new options menu (simple gear icon with dropdown menu). When you click on it you get submission dates (we don't store hashes or commit messages). Clicking on date should rerender the diff and its line comments (comments under submission should be shared across all attempts).  

**Potential problems**
Right now our db enforces unique index `@@unique([userId, lessonId, challengeId])` meaning that one user can have only one submission per challenge. If I remove this restriction it would be possible to submit multiply files for the same challenge (say submission A, B and C being the latest). When reviewer opens the page he will get all three submissions. If reviewer accepts A what should happen with B and C and vice versa?

One possible solution is to close all other submissions by the same user on clicking accept/reject (reviewer rejects B, A and C are also being rejected). Another way is to close previous attempt on re submission, meaning that B closes A, and C closes B, so only one submission is active at any time.

**Comment by ggwadera** [comment]
If possible I'd like to keep the state of previous submissions unchanged, just so we can keep a history of accepted or rejected submissions for a given challenge, meaning not accepting/rejecting all previous submissions. This way we can also get better statistics on Metabase.

One issue that may appear is someone resubmitting when the submission hasn't been reviewed yet, which would leave 2 `OPEN` submissions from the same user. For this case I suggest adding a new `OUTDATED` status for the submission table so the previous submission is not considered for review. Or just replace the newest open one if you don't wanna have any more trouble.
