### ISSUE TITLE
Improve the review comment editor/renderer

### ISSUE THREAD

**Issue by ggwadera** [garageScript/c0d3-app#894]
Our current markdown editor when adding a comment leaves a lot to be desired. The review experience could be a lot better by improving the editor. Sometimes I have to open VS Code just to type a more lengthy review that sometimes include code blocks.

The actual editor is just a `textarea` tag with monospaced font, so it's not a very smart editor.

https://github.com/garageScript/c0d3-app/blob/a2228dfe28a102aee68866e4a4bc41cf8af8b851/components/MdInput.tsx#L44-L50

Here's some things that could be improved.

- Code highlighting in the preview and comment view.
- Text area being reset when switching between write and preview (#869)
- More explicit markdown formatting options. Many students don't know markdown syntax and having buttons to add a heading, lists, or code, could be helpful. Look at the github editor for inspiration.
- Add some *smart* behaviors, like adding surrounding quotes (or braces, parenthesis, whatever) when you have part of the text selected, instead of just replacing it with only the opening character.

These could all be coded into our current components, or also through a new npm dependency. I'll leave this choice to the developer that wants to implement this.

**Comment by tomrule007** [comment]
I agree a lot could be improved here. The switching between write and preview resizing was driving me nuts.

It might be the best to go with a prebuilt option like this facebook package draft-js https://github.com/facebook/draft-js

**Comment by songz** [comment]
Closing because we rolled out a spanking awesome editor! https://github.com/garageScript/c0d3-app/issues/1010
