### ISSUE TITLE
Should we remove all env variables from next.config.js

### ISSUE THREAD

**Issue by tomrule007** [garageScript/c0d3-app#916]
We currently have our environment variables defined in our [next.config.js](https://github.com/garageScript/c0d3-app/blob/master/next.config.js) but it appears to be an artifact of an old version of Next.

(as @ggwadera  pointed out here https://github.com/garageScript/c0d3-app/issues/906#issuecomment-869694620 )

Benefits
- Removes an extra location to hide default values (all env variables should be in the `.env` file
- Extra Security preventing keys from accidentally being leaked to the frontend code. (Next will only expose keys with `NEXT_PUBLIC_*` prefix to the frontend)
-
cons
- ??

I'm still getting up to speed on typescript / next / c0d3-app so I might be missing something but It seems to be working on my end and maybe we can deploy a demo branch on vercel to confirm its working there as well.

**Comment by hwong0305** [comment]
Since this is no longer needed, I think the logging PR is a good time to make this refactor!

**Comment by tomrule007** [comment]
rolled into issue #906
