### ISSUE TITLE
Improve graphql mocking

### ISSUE THREAD

**Issue by Ulisseus** [garageScript/c0d3-app#928]
Grapql has a certain (really annoying IMO) feature, it fails silently if your mocked data doesn't conform to its type definitions. In such case it returns `undefined, undefined, undefined` for `data, loading, error` which is really confusing. And even if you know about such quirk of MockedProvider creating complex mocked objects in plain javascript  files is rather annoying (I ended up copying data from production most of the time). 

I propose the following:
- [x] Move all dummy data to typescript files.
- [ ] Move as much mock data from tests to dummy folder. You shouldn't define big complex objects in tests files. 
- [ ] Maybe even move storybook data to dummy folder.

This way we'll get a single source of truth of always correctly typed data.

**Comment by flacial** [comment]
Closed in favor of https://github.com/garageScript/c0d3-app/issues/1822
