### ISSUE TITLE
Automatically focus the first field of forms.

### ISSUE THREAD

**Issue by JasirZaeem** [garageScript/c0d3-app#968]
On pages like login, sign up, reset password and forgot password the only thing to do is fill the form on those pages.
So it would be better ux to automatically focus the fields there so that the user may immediately begin filling it.

e.g.
![image](https://user-images.githubusercontent.com/20666236/126473252-cd25364c-d313-4dd6-a6ea-cdf057b40287.png)

**Comment by ggwadera** [comment]
Fixed on #969
