### ISSUE TITLE
Bug Hydration Mismatches

### ISSUE THREAD

**Issue by tomrule007** [garageScript/c0d3-app#976]
## Bug: Hydration Mismatch
  server render does not match client render on first load
![hydrationMismatch](https://user-images.githubusercontent.com/17365077/126851837-9b3fb76d-6866-4fab-b01b-85e516720ac8.png)

**Environment:** local dev machine, current master: f7ef11b67de6b48be943600b7259a0fa3d4726e2

**Reproduce:** first load into `/curriculum`

## Details
NextJs Provides a lot of cool features but it can also produce some sneaky gotchas like this one.

When NextJS builds our pages it runs the page components server side and generates the first html file with the intial nodes already loaded. When a user request a page it sends that prebuilt html page which loads really fast and can be painted on the browser before any javascript has been parsed. (ideally this first view should be as close to the end result as possible). Then once the javascript loads react runs `reactDOM.hydrate()` instead of the normal `reactDOM.render()`.
 
Hydrate is really fast because it doesn't do any node diffs and just expects the trees to be the same as the server while it attaches all the event listeners. So if the trees don't match we can run into issues with nodes being misidentified by react

_\*\* My explination might be partial wrong but I think it's close enough and i've included more reading material on the topic below_

## How to prevent
Don't use any code outside of a useEffect block that may return different results on the server and client IE any code that depends on `window` or `document` will likely return different results as those nodes don't exist server side. Also and issue with graphql queries as those can run server side but can be blocked with the `{ssr: false}` 

**Further reading material**
- https://www.joshwcomeau.com/react/the-perils-of-rehydration/
- https://aboutmonica.com/blog/server-side-rendering-react-hydration-best-practices
- https://www.apollographql.com/blog/apollo-client/next-js/next-js-getting-started/
- https://tech.willhaben.at/how-to-shoot-yourself-in-the-foot-in-react-401e7dbba720

**Comment by flacial** [comment]
Has been fixed in #976
