### ISSUE TITLE
Moving to static layout and updating tests

### ISSUE THREAD

**Issue by tomrule007** [garageScript/c0d3-app#993]
I thought we were going to have an issue moving to the `getLayout` pattern (https://nextjs.org/docs/basic-features/layouts#per-page-layouts) because it removes the layout from the page that some of our page tests rely on.

Those tests can easily be fixed by wrapping the component in it's own `getLayout` call like this
https://github.com/garageScript/c0d3-app/blob/4d1cebcbdbfbdbb8134fd75ef9038372bc39623f/__tests__/pages/forgotpassword.test.js#L43

But I think it actually cleaner to leave the layout out of the snap shot as it really just adds a lot of noise to the screen shot when 90% of the time we a really just making sure the page matches some set of input props with the layout never changing.

So if we move forward with this move we could have one set of really nice tests for the layout component that just mocks next/router and makes sure all the route links work as expected and then a bunch of separate page snapshots without all the extra noise of the layout in each screen shot and then if there are any pages that need the layout for testing we can still wrap it like above.

Curious if anyone sees any issues of separating the layout from the page component that I might be missing?

**Comment by ggwadera** [comment]
I like it, was even wondering if some pages/components really need the whole layout to be tested like you said. Because of this some test failures are really hard to debug because of the huge snapshot that gets printed out.
